### ISSUE TITLE
customer create/update page

### ISSUE THREAD

**Issue by ashleygwilliams** [artisan-tattoo/assistant-frontend#5]
the customer create/update page creates a form for entering a name and an email address
model: https://github.com/artisan-tattoo/assistant-api/blob/master/db/schema.rb#L39-L53

the customer create/update page is viewable by the artist and the shop

**Comment by steveklabnik** [comment]
https://github.com/steveklabnik/artisantattoogallery.com/blob/master/artisan.rb#L57-L64 <- status codes, for reference

**Comment by steveklabnik** [comment]
this is done
